CREATE DATABASE myStoreDB;
USE myStoreDB;

DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;
DROP TABLE PRODUCTS;

CREATE TABLE PRODUCTS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(255) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    Description TEXT,
    CONSTRAINT CHK_Price CHECK(Price >= 0)
);

CREATE TABLE CUSTOMERS (
	CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Phone VARCHAR(10),
    Age INT,
    CONSTRAINT UQ_Email UNIQUE (Email),
    CONSTRAINT CHK_Age CHECK (Age >= 0)
);

CREATE TABLE ORDERS (
	OrderID INT PRIMARY KEY AUTO_INCREMENT,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    TotalAmount DECIMAL(18,2) NOT NULL,
    CustomerID INT,
    CONSTRAINT CHK_TotalAmount CHECK (TotalAmount >= 0),
    CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);